service: stakinet

package:
  exclude:
    - db.ref/**
    - handler.ref.js

provider:
  name: aws
  runtime: nodejs6.10
  cfLogs: true
  timeout: 20
  stage: development
  region: ap-northeast-1
  environment:
    LONESMOKE_MONGO_URI: ${file(./config.yml):lonesmokeMongoUri}
    NJ2JP_MONGO_URI: ${file(./config.yml):nj2jpMongoUri}

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true # enable auto including node_modules

functions:
  modifyMongo:
    handler: handler.modifyMongo
    vpc:
      securityGroupIds:
        - ${file(./config.yml):securityGroupId}
      subnetIds:
        - ${file(./config.yml):subnetId}
    iamRoleStatements:
      - Effect: Allow
        Resource: "*"
        Action:
          - ec2:CreateNetworkInterface
          - ec2:DescribeNetworkInterfaces
          - ec2:DetachNetworkInterface
          - ec2:DeleteNetworkInterface
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
    events:
      - http:
          path: modify
          method: post
          integration: lambda
          memorySize: 256
          timeout: 10
          cors: true
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
