service: stakinet-mongo-modify

package:
  exclude:
    - db.ref/**
    - handler.ref.js

provider:
  name: aws
  runtime: nodejs6.10
  cfLogs: true
  timeout: 20
  stage: development
  region: ap-northeast-1
  environment:
    MONGO_URI: ${file(./config.yml):mongoURI}

plugins:
  - serverless-webpack
  - serverless-eslint-plugin

custom:
  webpackIncludeModules: true # enable auto including node_modules

functions:
  mdodifyMongo:
    handler: handler.mdodifyMongo
    vpc:
      securityGroupIds:
        - ${file(./config.yml):securityGroupId}
      subnetIds:
        - ${file(./config.yml):subnetId}
    iamRoleStatements:
      - Effect: Allow
        Resource: "*"
        Action:
          - ec2:CreateNetworkInterface
          - ec2:DescribeNetworkInterfaces
          - ec2:DetachNetworkInterface
          - ec2:DeleteNetworkInterface
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
    events:
      - http:
          path: modify-mongo
          method: post
          integration: lambda
          memorySize: 256
          timeout: 10
          cors: true
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
